### ISSUE TITLE
下载报错:unexpected end of stream

### ISSUE THREAD

**Issue by zhoutianjin** [ixuea/android-downloader#15]
**Android Downloader version**:2.0.4
**Android Version**:9
**Issue details/Repro steps**:
1.不是总是不成功,大部分时候都成功
2.大部分时候都正常,10次大概会报错2次.

**Use code**:
```
downloadInfo.setDownloadListener(new DownloadListener() {

      @Override
      public void onStart() {
        Log.d(TAG, "准备开始");
      }

      @Override
      public void onWaited() {
        Log.d(TAG, "正在等待..可暂停");
      }

      @Override
      public void onPaused() {
        Log.d(TAG, "继续..可暂停");
      }

      @Override
      public void onDownloading(long progress, long size) {
        //Log.d(TAG, "进度:" + progress + ",总大小:" + size + ",可暂停");
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
          progressBar.setProgress((int) (progress * 100f / size), true);
        } else {
          progressBar.setProgress((int) (progress * 100f / size));
        }
        //Log.d(TAG, "progress:" + progress);
        commit.setText((int)(progress/(1024*1024))+"M/"+(int)(size/(1024*1024))+"M");
      }

      @Override
      public void onRemoved() {
        Log.d(TAG, "removedDown移除");
      }

      @Override
      public void onDownloadSuccess() {
        Log.d(TAG, "Download success成功");
      }

      @Override
      public void onDownloadFailed(DownloadException e) {
        Log.d(TAG, "onDownloadFailed错误");
        e.printStackTrace();
      }
    });
```

**Stack trace**:
```
2019-05-03 20:48:05.715 10624-10661/com.iniyun.rx_android_demo D/DownloadResponseImpl: progress:104569952,size:105281352
2019-05-03 20:48:05.717 10624-10624/com.iniyun.rx_android_demo W/System.err: com.ixuea.android.downloader.exception.DownloadException: Protocol error
2019-05-03 20:48:05.718 10624-10624/com.iniyun.rx_android_demo W/System.err:     at com.ixuea.android.downloader.core.thread.DownloadThread.executeDownload(DownloadThread.java:125)
2019-05-03 20:48:05.718 10624-10624/com.iniyun.rx_android_demo W/System.err:     at com.ixuea.android.downloader.core.thread.DownloadThread.run(DownloadThread.java:56)
2019-05-03 20:48:05.718 10624-10624/com.iniyun.rx_android_demo W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
2019-05-03 20:48:05.718 10624-10624/com.iniyun.rx_android_demo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-05-03 20:48:05.719 10624-10624/com.iniyun.rx_android_demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-05-03 20:48:05.719 10624-10624/com.iniyun.rx_android_demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-05-03 20:48:05.719 10624-10624/com.iniyun.rx_android_demo W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-05-03 20:48:05.721 10624-10624/com.iniyun.rx_android_demo W/System.err: Caused by: java.net.ProtocolException: unexpected end of stream
2019-05-03 20:48:05.722 10624-10624/com.iniyun.rx_android_demo W/System.err:     at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:396)
2019-05-03 20:48:05.723 10624-10624/com.iniyun.rx_android_demo W/System.err:     at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
2019-05-03 20:48:05.723 10624-10624/com.iniyun.rx_android_demo W/System.err:     at java.io.InputStream.read(InputStream.java:101)
2019-05-03 20:48:05.724 10624-10624/com.iniyun.rx_android_demo W/System.err:     at com.ixuea.android.downloader.core.thread.DownloadThread.executeDownload(DownloadThread.java:97)
2019-05-03 20:48:05.724 10624-10624/com.iniyun.rx_android_demo W/System.err: 	... 6 more

```

**Screenshot(if any)**:
app没崩溃,只是下载进度停留在60-90%之间位置.

**Comment by zhoutianjin** [comment]
希望作者修复,谢谢!
有希望下载交流的朋友,
欢迎联系:124360@qq.com

**Comment by ixueadev** [comment]
Thank you very much for your feedback. The problem has been fixed. If there are still problems, feel free to feedback or submit pr.
